version: '2'

services:

#  application:
#    image: cweagans/bg-sync
#    volumes:
#      - .:/source
#      - /var/www/application
#    environment:
#      - SYNC_DESTINATION=/var/www/application
#      - SYNC_MAX_INOTIFY_WATCHES=40000
#      - SYNC_VERBOSE=1
#    privileged: true

  application:
    image: tianon/true
    volumes:
      - .:/var/www/application

  mysql:
    image: mysql:5.6
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: noitacilppa
      MYSQL_USER: application
      MYSQL_PASSWORD: noitacilppa
      MYSQL_DATABASE: application
  nginx:
    image: nginx:1.13
    ports:
      - "80:80"
    volumes_from:
      - application:rw
    environment:
      NGINX_WEBROOT: "/var/www/application/Web"
      NGINX_PHP_HOST_AND_PORT: php:9000
      NGINX_SERVERNAME: application-dev
    volumes:
        - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  php:
    image: danmarksradio/docker-twa-php-71:local
    volumes_from:
      - application:rw
    environment:
      XDEBUG_CONFIG: remote_host=172.17.0.1
      PCO_ENV: dev
      FLOW_CONTEXT: Development/Docker
