version: '2'

services:

  application:
    image: tianon/true
    volumes:
      - .:/var/www/application
    labels:
      - "traefik.enable=false"

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    labels:
      - "traefik.enable=false"

  nginx:
    image: nginx:1.13
    volumes_from:
      - application:rw
    environment:
      NGINX_WEBROOT: "/var/www/application/Web"
      NGINX_PHP_HOST_AND_PORT: php:9000
      NGINX_SERVERNAME: application-dev
    volumes:
        - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    labels:
      - "traefik.backend=telegraph"
      - "traefik.frontend.rule=Host:telegraph.anne.flab.dk"
    ports:
      - "80:80"

  php:
    image: danmarksradio/docker-twa-php-71:develop
    volumes_from:
      - application:rw
    environment:
      FLOW_CONTEXT: "${FLOW_CONTEXT}"
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    labels:
      - "traefik.enable=false"
