

-
  name: 'Telegraph checkStatus'
  uriPattern: 'telegraph/{token}/checkStatus'
  defaults:
    '@package':    'Langeland.Telegraph'
    '@controller': 'Telegraph'
    '@action':     'checkStatus'

-
  name: 'Telegraph deliverTelegrams'
  uriPattern: 'telegraph/{token}/deliver/{type}'
  defaults:
    '@package':    'Langeland.Telegraph'
    '@controller': 'Telegraph'
    '@action':     'deliverTelegrams'

-
  name: 'Telegraph deliverTelegrams'
  uriPattern: 'telegraph/{token}/listTelegrams(/{type})'
  defaults:
    '@package':    'Langeland.Telegraph'
    '@controller': 'Telegraph'
    '@action':     'listTelegrams'
    'type': ''

