<?php
namespace Neos\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs! This block will be used as the migration description if getDescription() is not used.
 */
class Version20180318080732 extends AbstractMigration
{

    /**
     * @return string
     */
    public function getDescription()
    {
        return '';
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on "mysql".');
        
        $this->addSql('CREATE TABLE langeland_telegraph_domain_model_telegraph (identifier VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, online TINYINT(1) NOT NULL, PRIMARY KEY(identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE langeland_telegraph_domain_model_token (id VARCHAR(255) NOT NULL, telegraph VARCHAR(255) DEFAULT NULL, token VARCHAR(255) NOT NULL, INDEX IDX_434CF08E8056211 (telegraph), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE langeland_telegraph_domain_model_telegram (identifier VARCHAR(255) NOT NULL, telegraph VARCHAR(255) DEFAULT NULL, created DATETIME NOT NULL, printed DATETIME DEFAULT NULL, channel VARCHAR(255) NOT NULL, instant TINYINT(1) NOT NULL, tag VARCHAR(255) NOT NULL, message VARCHAR(65535) NOT NULL, messageencoded MEDIUMTEXT DEFAULT NULL, INDEX IDX_A3D1D89C8056211 (telegraph), PRIMARY KEY(identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('ALTER TABLE langeland_telegraph_domain_model_token ADD CONSTRAINT FK_434CF08E8056211 FOREIGN KEY (telegraph) REFERENCES langeland_telegraph_domain_model_telegraph (identifier)');
        $this->addSql('ALTER TABLE langeland_telegraph_domain_model_telegram ADD CONSTRAINT FK_A3D1D89C8056211 FOREIGN KEY (telegraph) REFERENCES langeland_telegraph_domain_model_telegraph (identifier)');
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on "mysql".');
        
        $this->addSql('ALTER TABLE langeland_telegraph_domain_model_token DROP FOREIGN KEY FK_434CF08E8056211');
        $this->addSql('ALTER TABLE langeland_telegraph_domain_model_telegram DROP FOREIGN KEY FK_A3D1D89C8056211');
        $this->addSql('DROP TABLE langeland_telegraph_domain_model_telegraph');
        $this->addSql('DROP TABLE langeland_telegraph_domain_model_token');
        $this->addSql('DROP TABLE langeland_telegraph_domain_model_telegram');
    }
}