<?php
namespace Neos\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs! This block will be used as the migration description if getDescription() is not used.
 */
class Version20180507091454 extends AbstractMigration
{

    /**
     * @return string
     */
    public function getDescription()
    {
        return '';
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on "mysql".');
        
        $this->addSql('CREATE TABLE langeland_telegraphcore_domain_model_telegram (identifier VARCHAR(255) NOT NULL, telegraph VARCHAR(255) DEFAULT NULL, created DATETIME NOT NULL, printed DATETIME DEFAULT NULL, channel VARCHAR(255) NOT NULL, instant TINYINT(1) NOT NULL, tag VARCHAR(255) DEFAULT NULL, message LONGTEXT NOT NULL, messageencoded LONGTEXT NOT NULL, INDEX IDX_49EFCCFE8056211 (telegraph), PRIMARY KEY(identifier)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE langeland_telegraphcore_domain_model_telegraph (identifier VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, online TINYINT(1) NOT NULL, PRIMARY KEY(identifier)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('ALTER TABLE langeland_telegraphcore_domain_model_telegram ADD CONSTRAINT FK_49EFCCFE8056211 FOREIGN KEY (telegraph) REFERENCES langeland_telegraphcore_domain_model_telegraph (identifier)');
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on "mysql".');
        
        $this->addSql('ALTER TABLE langeland_telegraphcore_domain_model_telegram DROP FOREIGN KEY FK_49EFCCFE8056211');
        $this->addSql('DROP TABLE langeland_telegraphcore_domain_model_telegram');
        $this->addSql('DROP TABLE langeland_telegraphcore_domain_model_telegraph');
    }
}