
-
  name: 'Langeland.TelegraphApi - Check status'
  uriPattern: 'telegraph/{telegraph}/checkstatus'
  defaults:
    '@package':    'Langeland.TelegraphApi'
    '@controller': 'telegraph'
    '@action':     'checkStatus'
    '@format':     'json'
    'telegraph': ''

-
  name: 'Langeland.TelegraphApi - Deliver telegrams'
  uriPattern: 'telegraph/{telegraph}/deliver/{type}'
  defaults:
    '@package':    'Langeland.TelegraphApi'
    '@controller': 'telegraph'
    '@action':     'deliverTelegrams'
    '@format':     'json'

-
  name: 'Langeland.TelegraphApi - List telegrams'
  uriPattern: 'telegraph/{telegraph}/telegrams(/{type})'
  defaults:
    '@package':    'Langeland.TelegraphApi'
    '@controller': 'telegraph'
    '@action':     'listTelegrams'
    '@format':     'json'
    'type': ''

-
  name: 'Push'
  uriPattern: 'telegraph/{telegraph}/push'
  defaults:
    '@package':    'Langeland.TelegraphApi'
    '@controller': 'telegraph'
    '@action':     'push'
    '@format':     'json'
    'type': ''


