
-
  name: 'Default'
  uriPattern: 'telegraph/{@action}'
  defaults:
    '@controller': 'telegraph'
    '@action':     'index'

-
  name: 'Default'
  uriPattern: 'telegraph/{@action}/{telegraph}'
  defaults:
    '@controller': 'telegraph'




-
  name: 'Default'
  uriPattern: 'telegram/{@action}'
  defaults:
    '@controller': 'telegram'


-
  name: 'Default'
  uriPattern: 'telegram/{@action}/{telegraph}'
  defaults:
    '@controller': 'telegram'
    'telegraph': ''



-
  name: 'Default'
  uriPattern: 'telegram/{@action}/{telegram}'
  defaults:
    '@controller': 'telegram'
    'telegram': ''





