##
# Telegraph subroutes
#

-
  name: 'Telegraph User Interface'
  uriPattern: 'ui/<TelegraphUserInterfaceSubroutes>'
#  defaults:
#    '@format': 'html'
  subRoutes:
    'TelegraphUserInterfaceSubroutes':
      package: 'Langeland.TelegraphUserInterface'