##
# Telegraph subroutes
#
-
  name: 'Telegraph Api'
  uriPattern: 'api/<TelegraphApiSubroutes>'
  defaults:
    '@format': 'html'
  subRoutes:
    'TelegraphApiSubroutes':
      package: 'Langeland.TelegraphApi'

-
  name: 'Telegraph User Interface'
  uriPattern: 'ui/<TelegraphUserInterfaceSubroutes>'
  defaults:
    '@package':    'Langeland.TelegraphUserInterface'
    '@format': 'html'
  subRoutes:
    'TelegraphUserInterfaceSubroutes':
      package: 'Langeland.TelegraphUserInterface'

