##
# Telegraph subroutes
#

-
  name: 'Telegraph User Interface'
  uriPattern: 'ui/<TelegraphUserInterfaceSubroutes>'
#  defaults:
#    '@format': 'html'
  subRoutes:
    'TelegraphUserInterfaceSubroutes':
      package: 'Langeland.TelegraphUserInterface'

-
  name: 'Telegraph Api'
  uriPattern: 'api/<TelegraphApiSubroutes>'
  defaults:
    '@format': 'html'
  subRoutes:
    'TelegraphApiSubroutes':
      package: 'Langeland.TelegraphApi'