Neos:
  Flow:
    mvc:
      routes:
        'Neos.Flow':
          position: 'end'
    persistence:
      backendOptions:
        doctrine:
          sqlLogger: 'Neos\Flow\Persistence\Doctrine\Logging\SqlLogger'
